// Generated by AI
using HomeHub.Application.Common.Pagination;
using HomeHub.Application.Features.ShoppingList.GetAllShoppingLists;
using HomeHub.Application.Features.ShoppingList.Interfaces;
using HomeHub.Domain.Entities;
using MediatR;

namespace HomeHub.Application.Features.ShoppingList.GetAllShoppingLists;

public class GetAllShoppingListsQueryHandler(IShoppingListRepository repository) : IRequestHandler<GetAllShoppingListsQuery, PaginationResult<Domain.Entities.ShoppingList>>
{
    public async Task<PaginationResult<Domain.Entities.ShoppingList>> Handle(GetAllShoppingListsQuery request, CancellationToken cancellationToken)
    {
        var paginatedResult = await repository.GetPaginatedAsync(request.PageNumber, request.PageSize, cancellationToken);

        return paginatedResult;
    }
}