// Generated by AI
using HomeHub.Application.Common.Pagination;
using HomeHub.Domain.Entities;
using MediatR;

namespace HomeHub.Application.Features.ShoppingList.GetAllShoppingLists;

public record GetAllShoppingListsQuery : PaginationQuery, IRequest<PaginationResult<Domain.Entities.ShoppingList>>
{

}