// Generated by AI
using HomeHub.Application.Features.ShoppingList.GenerateShoppingList;
using HomeHub.Application.Features.ShoppingList.GetAllShoppingLists;
using HomeHub.Application.Features.ShoppingList.GetShoppingListById;
using MediatR;
using Microsoft.AspNetCore.Mvc;

namespace HomeHub.Api.Controllers;

[ApiController]
[Route("api/[controller]")]
public class ShoppingListController(IMediator mediator) : ControllerBase
{
    [HttpGet("{id}")]
    public async Task<IActionResult> GetById([FromRoute] Guid id)
    {
        var result = await mediator.Send(new GetShoppingListByIdQuery(id));
        return Ok(result);
    }

    [HttpGet]
    public async Task<IActionResult> GetAll([FromQuery] GetAllShoppingListsQuery query)
    {
        var result = await mediator.Send(query);
        return Ok(result);
    }

    [HttpPost("generate")]
    public async Task<IActionResult> Generate()
    {
        var id = await mediator.Send(new GenerateShoppingListCommand());
        return CreatedAtAction(nameof(GetById), new { id }, id);
    }
}