// Generated by AI
using HomeHub.Application.Features.ShoppingList.GetShoppingListById;
using HomeHub.Application.Features.ShoppingList.Interfaces;
using HomeHub.Domain.Entities;
using MediatR;

namespace HomeHub.Application.Features.ShoppingList.GetShoppingListById;

public class GetShoppingListByIdQueryHandler(IShoppingListRepository repository) : IRequestHandler<GetShoppingListByIdQuery, Domain.Entities.ShoppingList>
{
    public async Task<Domain.Entities.ShoppingList> Handle(GetShoppingListByIdQuery request, CancellationToken cancellationToken)
    {
        var shoppingList = await repository.GetByIdAsync(request.Id, cancellationToken);

        if (shoppingList is null)
        {
            throw new KeyNotFoundException($"Shopping list with ID {request.Id} was not found.");
        }

        return shoppingList;
    }
}