// Generated by AI
using HomeHub.Domain.Entities;
using MediatR;

namespace HomeHub.Application.Features.ShoppingList.GetShoppingListById;

public record GetShoppingListByIdQuery(Guid Id) : IRequest<Domain.Entities.ShoppingList>
{

}